version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
    - "3306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=mypassword

  redis:
    image: redis:4
    container_name: redis
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"

  php:
    build: ./php-fpm
    container_name: php
    hostname: php
    ports:
    - "9000:9000"
    # easyswoole 端口
    #- "9501:9501"
    links:
    - mysql:mysql
    - redis:redis
    volumes:
    - /volumes/data/source:/volumes/data/source
    - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    - ./php-fpm/cron/laravel:/var/spool/cron/crontabs/laravel
    - ./php-fpm/supervisor/program.conf:/etc/supervisor/conf.d/program.conf
    command: supervisord -c /etc/supervisor/supervisord.conf
    working_dir: /volumes/data/source

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
    - "80:80"
    volumes:
    - /volumes/data/source:/volumes/data/source
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    links:
    - php:PHP-FPM

#  phpMyAdmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: phpmyadmin
#    ports:
#      # 用8081端口，避免与apache端口冲突
#      - "8081:80"
#    links:
#      - mysql:mysql
#    volumes:
#      - /sessions
#      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
#    environment:
#      - PMA_HOST=mysql

#  node:
#    image: node:latest
#    container_name: node
#    hostname: node
#    ports:
#    - "7001:7001"
#    working_dir: /volumes/data/source
#    links:
#    - redis:redis
#    volumes:
#    - /volumes/data/source:/volumes/data/source
#    # >在字符串中折叠换行，| 保留换行符，这两个符号是YAML中字符串经常使用的符号
#    #  command:
#    #     - /bin/sh
#    #     - -c
#    #     - |
#    #     yarn install
#    #     pm2-runtime start ecosystem.config.js
#    command: ["/bin/sh", "-c", "yarn install && yarn dev"]